In [1]:
import os
import numpy
import scipy.io
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
import os
os.environ['LD_LIBRARY_PATH'] = '/jupyter/instantclient_18_3:/usr/local/cuda/extras/CUPTI/lib64:/usr/local/nvidia/lib:/usr/local/nvidia/lib64'
os.environ['PATH'] = '/jupyter/instantclient_18_3:/usr/local/mpi/bin:/usr/local/nvidia/bin:/usr/local/cuda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
os.environ['ORACLE_HOME']='/jupyter/instantclient_18_3'
os.environ['DYLD_LIBRARY_PATH']='/jupyter/instantclient_18_3'

In [3]:
STA = 'STKA'

In [4]:
#load data from oracle do pandas
#connect to udb
#with open(os.path.join('/','home','hofman','.dbp.txt'), 'r') as f: password_old = f.read().strip()
password_old = "Gagulinecicek#2015"
import cx_Oracle
connection = cx_Oracle.connect('hofman', password_old, 'udb')

DatabaseError: ORA-12154: TNS:could not resolve the connect identifier specified

In [86]:
from datetime import datetime as dt
ts_2017 = dt(2017,1,1,0,0,0).timestamp()
ts_2018 = dt(2018,1,1,0,0,0).timestamp()
ts_2019 = dt(2019,1,1,0,0,0).timestamp()

In [89]:
query = f"select * from EVAL_QANDEF"   ## where sta='{STA}'"
df_all_ = pd.read_sql(query, con=connection)

In [90]:
df_all_.shape

(48071, 12)

In [96]:
ind = [{False: True, True:False}[x] for x in numpy.isnan(df_all_['NCLS_PHASE_ODB'])]

In [99]:
ind

[True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,

In [100]:
df_all = df_all_[ind]

In [101]:
df_all.head()

ARID_ODB      TIME_ODB     AZI_ODB IPHASE_QANDEF IPHASE_ODB ASSOC_PHASE  \
0  130466588  1.520198e+09    5.636480             N         Pn        None   
1  130466904  1.520199e+09  154.610430             P          P        None   
2  130466998  1.520200e+09   34.084353             P          P        None   
3  130467276  1.520201e+09  282.437680             P          P        None   
4  130467277  1.520201e+09  168.726310             P          P        None   

  CLASS_IPHASE_QANDEF CLASS_IPHASE_ODB CLASS_PHASE_ODB  NCLS_IPHASE_QANDEF  \
0                   N             regP               N                   0   
1                   T                T               N                   1   
2                   T                T               N                   1   
3                   T                T               N                   1   
4                   T                T               N                   1   

   NCLS_IPHASE_ODB  NCLS_PHASE_ODB  
0                2             0.0  
1                1             0.0  
2                1             0.0  
3                1             0.0  
4                1             0.0

In [105]:
import warnings

with warnings.catch_warnings():
    warnings.simplefilter("ignore")
    NCLS_IPHASE_QANDEF = df_all['NCLS_IPHASE_QANDEF'].as_matrix()
    NCLS_IPHASE_ODB = df_all['NCLS_IPHASE_ODB'].as_matrix()
    NCLS_PHASE_ODB = numpy.array(df_all['NCLS_PHASE_ODB'].as_matrix(), dtype=numpy.int)

In [106]:
NCLS_PHASE_ODB.min(), NCLS_PHASE_ODB.max()

(0, 3)

In [107]:
df_all[numpy.isnan(df_all['NCLS_PHASE_ODB'])]


Empty DataFrame
Columns: [ARID_ODB, TIME_ODB, AZI_ODB, IPHASE_QANDEF, IPHASE_ODB, ASSOC_PHASE, CLASS_IPHASE_QANDEF, CLASS_IPHASE_ODB, CLASS_PHASE_ODB, NCLS_IPHASE_QANDEF, NCLS_IPHASE_ODB, NCLS_PHASE_ODB]
Index: []

In [108]:
from sklearn.metrics import confusion_matrix

In [111]:
def confmat(x,y):
    C = confusion_matrix(x,y)
    diagsum = numpy.diag(C).sum()
    accuracy = diagsum/C.sum()
    print (C)
    print('Assoc accuracy: %3.2f%%' % ((numpy.diag(C)[1:].sum())/(C[:,1:].sum())*100))
    print('Overal accuracy: %3.2f%%' % (accuracy*100))
    print('N phase rate: %3.2f%%' % (C[0,1:].sum()/C[:,1:].sum()*100))

In [113]:
#confusion_matrix(y_true, y_pred)
print('OLD:')
confmat(NCLS_IPHASE_ODB, NCLS_PHASE_ODB)

print('NEW')
confmat(NCLS_IPHASE_QANDEF, NCLS_PHASE_ODB)

OLD:
[[12263   195     0    14]
 [24967  2922   129     5]
 [ 5569   501    73     3]
 [ 1364    58     0     7]]
Assoc accuracy: 76.84%
Overal accuracy: 31.76%
N phase rate: 5.35%
NEW
[[19893   125     2     9]
 [19559  3022   124     4]
 [ 3138   401    76     6]
 [ 1573   128     0    10]]
Assoc accuracy: 79.55%
Overal accuracy: 47.85%
N phase rate: 3.48%
